# Generated by Django 4.0.5 on 2022-06-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='ingredient_name',
        ),
    ]
